name: Bug Report
description: Report broken or incorrect behaviour.
labels: ["Bug::Library"]
title: "[BUG] Your Title Here"

assignees:
  - LordOfPolls
body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to fill out a bug report.
        If you want real-time support, consider joining our [Discord](https://discord.gg/naff) instead.

  - type: input
    attributes:
      label: NAFF Version
      description: What version of the library you are currently running.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the Bug
      description: A simple summary of your bug report
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Results
      description: >
        A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Minimal Reproducible Code
      description: >
        A short snippet of code that showcases the bug.
      render: python
  - type: textarea
    attributes:
      label: Traceback
      description: >
        Was there a traceback?
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Checklist
      description: >
        Let's make sure you've properly done due diligence when reporting this issue!
      options:
        - label: I have searched the open issues for duplicates.
          required: true
        - label: I have shown the entire traceback, if possible.
          required: true
        - label: I have removed my token from display, if visible.
          required: true
  - type: textarea
    attributes:
      label: Additional Information
      description: Any other information about the problem.
